//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMEA_connector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NMEA_connector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Run GPS command.
        /// </summary>
        public static string ConsolUi_ConsolInit__1__Run_GPS_command {
            get {
                return ResourceManager.GetString("ConsolUi_ConsolInit__1__Run_GPS_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Show GPS Time.
        /// </summary>
        public static string ConsolUi_ConsolInit__2__Show_GPS_Time {
            get {
                return ResourceManager.GetString("ConsolUi_ConsolInit__2__Show_GPS_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Show GPS Longitude-Latitude.
        /// </summary>
        public static string ConsolUi_ConsolInit__3__Show_GPS_Longitude_Latitude {
            get {
                return ResourceManager.GetString("ConsolUi_ConsolInit__3__Show_GPS_Longitude_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Print out GPS data.
        /// </summary>
        public static string ConsolUi_ConsolInit__4__Print_out_GPS_data {
            get {
                return ResourceManager.GetString("ConsolUi_ConsolInit__4__Print_out_GPS_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Exit.
        /// </summary>
        public static string ConsolUi_ConsolInit__9__Exit {
            get {
                return ResourceManager.GetString("ConsolUi_ConsolInit__9__Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS_menu.
        /// </summary>
        public static string ConsolUi_ConsolInit_GPS_menu {
            get {
                return ResourceManager.GetString("ConsolUi_ConsolInit_GPS_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMEA og Device config.
        /// </summary>
        public static string ConsolUi_ConsolInit_NMEA_og_Device_config {
            get {
                return ResourceManager.GetString("ConsolUi_ConsolInit_NMEA_og_Device_config", resourceCulture);
            }
        }
    }
}
