var annotated_dup =
[
    [ "nmea_connector", "namespacenmea__connector.html", "namespacenmea__connector" ],
    [ "NMEA_connector", "namespace_n_m_e_a__connector.html", "namespace_n_m_e_a__connector" ],
    [ "__COMM_EVENTS", "struct_____c_o_m_m___e_v_e_n_t_s.html", "struct_____c_o_m_m___e_v_e_n_t_s" ],
    [ "__HW_INDEP_INFO", "struct_____h_w___i_n_d_e_p___i_n_f_o.html", "struct_____h_w___i_n_d_e_p___i_n_f_o" ],
    [ "__HW_OPEN_INFO", "struct_____h_w___o_p_e_n___i_n_f_o.html", "struct_____h_w___o_p_e_n___i_n_f_o" ],
    [ "__RX_BUFFER_INFO", "struct_____r_x___b_u_f_f_e_r___i_n_f_o.html", "struct_____r_x___b_u_f_f_e_r___i_n_f_o" ],
    [ "__SER_INFO", "struct_____s_e_r___i_n_f_o.html", "struct_____s_e_r___i_n_f_o" ],
    [ "__TX_BUFFER_INFO", "struct_____t_x___b_u_f_f_e_r___i_n_f_o.html", "struct_____t_x___b_u_f_f_e_r___i_n_f_o" ],
    [ "_nmeaGENERATOR", "struct__nmea_g_e_n_e_r_a_t_o_r.html", "struct__nmea_g_e_n_e_r_a_t_o_r" ],
    [ "_nmeaGPGGA", "struct__nmea_g_p_g_g_a.html", "struct__nmea_g_p_g_g_a" ],
    [ "_nmeaGPGSA", "struct__nmea_g_p_g_s_a.html", "struct__nmea_g_p_g_s_a" ],
    [ "_nmeaGPGSV", "struct__nmea_g_p_g_s_v.html", "struct__nmea_g_p_g_s_v" ],
    [ "_nmeaGPRMC", "struct__nmea_g_p_r_m_c.html", "struct__nmea_g_p_r_m_c" ],
    [ "_nmeaGPVTG", "struct__nmea_g_p_v_t_g.html", "struct__nmea_g_p_v_t_g" ],
    [ "_nmeaINFO", "struct__nmea_i_n_f_o.html", "struct__nmea_i_n_f_o" ],
    [ "_nmeaPARSER", "struct__nmea_p_a_r_s_e_r.html", "struct__nmea_p_a_r_s_e_r" ],
    [ "_nmeaParserNODE", "struct__nmea_parser_n_o_d_e.html", "struct__nmea_parser_n_o_d_e" ],
    [ "_nmeaPOS", "struct__nmea_p_o_s.html", "struct__nmea_p_o_s" ],
    [ "_nmeaPROPERTY", "struct__nmea_p_r_o_p_e_r_t_y.html", "struct__nmea_p_r_o_p_e_r_t_y" ],
    [ "_nmeaSATELLITE", "struct__nmea_s_a_t_e_l_l_i_t_e.html", "struct__nmea_s_a_t_e_l_l_i_t_e" ],
    [ "_nmeaSATINFO", "struct__nmea_s_a_t_i_n_f_o.html", "struct__nmea_s_a_t_i_n_f_o" ],
    [ "_nmeaTIME", "struct__nmea_t_i_m_e.html", "struct__nmea_t_i_m_e" ],
    [ "_VGD_INFO", "struct___v_g_d___i_n_f_o.html", "struct___v_g_d___i_n_f_o" ],
    [ "CMainDlg", "class_c_main_dlg.html", "class_c_main_dlg" ],
    [ "CMainTab", "class_c_main_tab.html", "class_c_main_tab" ],
    [ "CPosTab", "class_c_pos_tab.html", "class_c_pos_tab" ],
    [ "CSignalTab", "class_c_signal_tab.html", "class_c_signal_tab" ],
    [ "DevHandler", "class_dev_handler.html", "class_dev_handler" ],
    [ "DevInfo", "struct_dev_info.html", "struct_dev_info" ],
    [ "DevManager", "class_dev_manager.html", "class_dev_manager" ]
];